name: Publish Snapshot

on:
  push:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  gradle:
    name: Gradle
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Export .java-version
      run: echo "JAVA_VERSION=$(head -1 .java-version)" >>"$GITHUB_ENV"
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ env.JAVA_VERSION }}
    - name: Run Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: publishSnapshot
